version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: bongso1_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bongso1_db
      MYSQL_USER: bongso1_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - bongso1_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bongso1_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bongso1_network

networks:
  bongso1_network:
    driver: bridge

volumes:
  mysql_data: